import {Component, OnInit, ViewChild, ViewContainerRef, ComponentFactoryResolver} from "@angular/core";
import {SimpleFormComponent} from "../simple-form/simple-form.component";

@Component({
  selector: 'app-home',
  templateUrl: './home.component.html',
  styleUrls: ['./home.component.css']
})
export class HomeComponent implements OnInit {

  @ViewChild('autoGeneratedForms', {read: ViewContainerRef}) container;

  constructor(private resolver: ComponentFactoryResolver) {
  }

  ngOnInit() {
  }

  ngAfterContentInit() {
    console.log(this.container);
    let componentFactory = this.resolver.resolveComponentFactory(SimpleFormComponent);
    this.container.createComponent(componentFactory);
    this.container.createComponent(componentFactory);
    this.container.createComponent(componentFactory);
    this.container.createComponent(componentFactory);
    let ref = this.container.createComponent(componentFactory);
    ref.instance.message = "I'm the last";

    let ref2 = this.container.createComponent(componentFactory, 2);
    ref2.instance.message = "I'm the third";
  }

  onClick() {
    let componentFactory = this.resolver.resolveComponentFactory(SimpleFormComponent);
    let ref = this.container.createComponent(componentFactory, 3);
    ref.instance.message = "I'm after the third";
  }

}
